version: '3.8'
services:
  database:
    image: postgres:alpine
    container_name: pgdatabase
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: memoire
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@scholarhub.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 15432:80
  #   depends_on:
  #     - database

  backend:
    image: shirley/scholarhub:backend
    container_name: backend
    ports:
      - '5000:5000'
    command: sh -c "sleep 20s; python launch.py"
    depends_on:
      - database