version: "3.8"
services:
  database:
    image: postgres:alpine
    container_name: pgdatabase
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: memoire
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  backend:
    image: tafitashirley/scholarhub-backend:v1
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=memoire
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=pgdatabase
    command: sh -c "sleep 10s; gunicorn -w 5 -b :5000 launch:app --reload"
    depends_on:
      - database

  frontend:
    image: tafitashirley/scholarhub-frontend:v1
    container_name: frontend
    ports:
      - "5001:5001"
    environment:
      - BACKEND_HOST=backend
    command: sh -c "sleep 15s; gunicorn -w 5 -b :5001 launch:app --reload"
    depends_on:
      - backend
