version: "3.8"
services:
  database:
    image: postgres:alpine
    container_name: pgdatabase
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: memoire
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - scholarhub:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # backend:
  #   image: shirley/scholarhub:backend
  #   container_name: backend
  #   ports:
  #     - '5000:5000'
  #   command: sh -c "sleep 20s; python launch.py"
  #   depends_on:
  #     - database
# volumes:
#   scholarhub:
