apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:latest
          command: ["sh", "-c", "until nc -z backend-service 5000; do sleep 1; done"]
      containers:
        - name: frontend-container
          image: tafitashirley/scholarhub-frontend:v1
          ports:
            - containerPort: 5001
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: backend-host

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
