from .categorie import route_categorie
from .titre import route_titre
from .encadreur import route_encadreur
from .parcours import route_parcours
from .etudiant import route_etudiant
from .niveau import route_niveau
from .annee import route_annee
from .etablissement import route_etablissement
from .inscription import route_inscription
from .livre import route_livre
from .redaction import route_redaction